version: '3.8'
services:
  app:
    build: 
      context: ./server
    container_name: nest-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/DATABASE_URL
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=DATABASE_URL
    volumes:
      - pg_data:/var/lib/postgresql/data
    
volumes:
  pg_data
